<h2><strong>🐍 Contribution Snake</strong></h2>

<p align="center">
  <picture>
    <source
      media="(prefers-color-scheme: dark)"
      srcset="https://raw.githubusercontent.com/neilarnobmittra/neilarnobmittra/output/github-snake-dark.svg"
    />
    <source
      media="(prefers-color-scheme: light)"
      srcset="https://raw.githubusercontent.com/neilarnobmittra/neilarnobmittra/output/github-snake.svg"
    />
    <img
      src="https://raw.githubusercontent.com/neilarnobmittra/neilarnobmittra/output/github-snake.svg"
      alt="GitHub Contribution Snake"
      width="600"
    />
  </picture>
</p>
